server:
  port: 80
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    #    register-with-eureka: false
    registerWithEureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
#      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-order-service
  # zipkin + sleuth监控
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  # consul注册中心地址
#  cloud:
#    consul:
#      host: 192.168.43.94
#      port: 8500
#      discovery:
#        # hostname127.0.0.1
#        service-name: ${spring.application.name}
#        heartbeat:
#          enabled: true