server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr:
        server-addr: 192.168.43.128:1111 # 配置nacos地址127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'