server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    # 路由的ID,没有固定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001          # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE     # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**            # 断言,路径相匹配的进行路由
        - id: payment_routh2 #payment_route    # 路由的ID,没有固定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001          # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE     # 匹配后提供服务的路由地址
          predicates:     # 断言
            - Path=/payment/lb/**            # 断言,路径相匹配的进行路由
#            - After=2020-08-10T10:02:25.263+08:00[Asia/Shanghai]
#            - Before=2020-08-10T10:02:25.263+08:00[Asia/Shanghai]
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2021-01-21T17:42:47.789-07:00[America/Denver]
#            - Cookie=username,czl
#            - Header=X-Request-Id, \d+      # 请求头要有X-Request-Id属性，并且值为正数的正则表达式
#            - Host=**.athome.com            # curl http://localhost:9527/payment/lb?red=greet -H "X-Request-Id:12" -H "Host:czl.athome.com"
#            - Method=GET
#            - Query=username, \d+           # 要有参数名username并且值是正数才能路由 (http://localhost:9527/payment/lb?username=31)
#            - Query=red, gree.              # 参数名red匹配值greet/green等将匹配
# 访问说明：添加网关前： http://localhost:8001/payment/get/31
#          添加网关后： http://localhost:9527/payment/get/31
#          filters:
#            - AddRequestHeader=X-Request, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client: # 服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
